### ISSUE TITLE
After i insert the sms key and pass not working keep loop

### ISSUE THREAD

**Issue by Renaenys** [dziungles/Coinwink#13] opened 2018-05-07 14:02 UTC
[https://ibb.co/gwykon](url)
Above images show after insert the key and password and press save it keep ask for key and pass

Settings updated!
Create SMS alert

after click
Create SMS alert it go back

API settings
Please configure
and unable to create alert

**Comment by giekaton** [comment] 2018-05-09 00:21
So were you able to find a solution for this? The problem is probably related to your development environment, as you can see on coinwink.com it works fine.

**Comment by giekaton** [comment] 2018-05-09 09:37
Also, try to create a new account. It may not be working because you are using the main admin account.

**Comment by giekaton** [comment] 2018-05-19 05:40
Closing this issue.

**Closed as completed by giekaton** 2018-05-19 05:40 UTC
